### ISSUE TITLE
Understand the Main Purpose of the Site

### ISSUE THREAD

**Issue by Aziz-Ibrahim** [Aziz-Ibrahim/Shinsei-academy#1]
**Title:** 
### [First-Time Visitor] Understand the main purpose of the site

**Description:** 
As a First-Time Visitor,I want to easily understand the main purpose of the site,
So I can learn more about the academy.

**Tasks:**

- [x] Write a concise and compelling vision and philosophy statements for the homepage.
- [x] Design a prominent hero section to display the mission statement.
- [x] Add supporting visuals or call-to-action buttons (e.g., "Learn More" or "Join Us").
- [x] Test the layout for responsiveness on mobile and desktop devices.

**Acceptance Criteria:**

- [x] A clear and concise mission statement is displayed prominently on the homepage.
- [x] The homepage includes visuals and/or headlines that describe the academy’s main offerings.
